### ISSUE TITLE
bug: replace this with a summary of the issue you're experiencing

### ISSUE THREAD

**Issue by DaviDiB1** [SoCuul/SCInsta#103]
I'm having the "Error: Process completed with exit code 1" and I see that when I try the direct like I have created, it sends me to "this file is too large" page so it does not start downloading right away. How do I fix this? 
<img width="1680" alt="Screenshot 2024-10-14 at 11 11 46 PM" src="https://github.com/user-attachments/assets/e952f6fc-781f-4f0a-aa01-54c81853464b">

**Comment by SoCuul** [comment]
This is not an issue to do with SCInsta. Please refer to other sources online or use one of the provided methods in the guide to host the ipa files.

**Comment by DaviDiB1** [comment]
Well couldn't do it with google drive or onedrive since they said the file was too big not stated in the guide. Had to do it with icloud, got it to work.
