### ISSUE TITLE
Scinsta V0.6.0 crashing because of emojiport

### ISSUE THREAD

**Issue by DaviDiB1** [SoCuul/SCInsta#104]
Tried downloading emojiport and wasn't able to open insta anymore. Deleted emojiport only not any of it's resources and insta started working again.

Iphone 14 pro dopamine rootless jailbroken on 16.1 
emojiport from poomsmart repo 
SCinsta v0.6.0
insta version v350.0.12

**Comment by SoCuul** [comment]
This issue is not related to SCInsta, so unfortunately I cannot provide support for this.
