### ISSUE TITLE
There was an issue during installation

### ISSUE THREAD

**Issue by Amrani-IT** [SoCuul/SCInsta#105]
<img width="461" alt="Screenshot 2024-10-22 at 14 48 07" src="https://github.com/user-attachments/assets/b0a34a39-9644-4e39-ad43-d860d05d94c0">

This is the error i get ! This is new - i used previous builds just fine.

**Comment by SoCuul** [comment]
This is not an issue with SCInsta, but instead with the installing process of the app. I would recommend deleting the installed version of Instagram app, and then installing the modded version again after the old version is uninstalled.

**Comment by Amrani-IT** [comment]
i made sure i removed it, interesting that the old version of insta works but 3.50 onwards doesn't
