### ISSUE TITLE
Build and Package SCInsta doesnt show anything

### ISSUE THREAD

**Issue by raphausler** [SoCuul/SCInsta#111]
![image_2024-11-13_001227464](https://github.com/user-attachments/assets/69b9a0ac-f032-4504-ba50-fde078347146)

**Comment by SoCuul** [comment]
Try deleting the repository, and forking it again. If it asks about allowing "github actions" from other users, click allow.

**Comment by raphausler** [comment]
Thank you. Injected it with .deb file via sideloadly and worked. But where can i find decrypted Instagram ipa file that works?

**Comment by SoCuul** [comment]
Unfortunately I can't directly provide that here, but if you search online it won't take more than 10 seconds haha.
