### ISSUE TITLE
feat: Just Message Insta

### ISSUE THREAD

**Issue by raphausler** [SoCuul/SCInsta#122]
I know there are already options to disable the Reels button and to prevent scrolling through Reels, but this would be a version designed to use Instagram without any distractions. It could be added as an option, like a button for just messages, which would also disable scrolling through Reels. The app could open directly to messages, and nothing else would be accessible. Logically the settings for SCInsta must be accessed differently if this option is active. Alternatively, a separate app could be created for this feature, as I’m not sure if it would be easy to add to the current version of SCInsta. I’m not an expert, so I’m not sure if this is possible, but it seems like a good idea. I think a lot of users would appreciate this feature.

**Comment by SoCuul** [comment]
This definitely seems like a good idea for many use cases, but I think it would be a little too niche for the scope of this tweak. Love the idea though, had actually came up with a similar one when brainstorming for original features to add to this tweak!
