### ISSUE TITLE
bug: v0.6.0 Bundle ID Prefix Error While Sideloading.

### ISSUE THREAD

**Issue by Bryan0211** [SoCuul/SCInsta#124]
### Error Code:
`minimuxer.MinimuxerError 0`
> The operation couldn’t be completed. Unable to install the app: Error Domain=IXErrorDomain Code=2 "Failed to set app extension placeholders for com.burbn.instagram.4493B2X8J7" UserInfo={NSLocalizedFailureReason=Failed to create promise., NSLocalizedDescription=Failed to set app extension placeholders for com.burbn.instagram.4493B2X8J7, FunctionName=+[IXPlaceholder _placeholderForBundle:client:withParent:installType:metadata:placeholderType:mayBeDeltaPackage:isFromSerializedPlaceholder:error:], SourceFileLine=968, NSUnderlyingError=0x6f8049f20 {Error Domain=IXErrorDomain Code=8 "Attempted to set app extension placeholder promise with bundle ID com.burbn.instagram.lockscreencamera that does not match required prefix of com.burbn.instagram.4493B2X8J7. for parent" UserInfo={NSLocalizedDescription=Attempted to set app extension placeholder promise with bundle ID com.burbn.instagram.lockscreencamera that does not match required prefix of com.burbn.instagram.4493B2X8J7. for parent, FunctionName=-[IXPlaceholder setAppExtensionPlaceholderPromises:error:], SourceFileLine=1582, NSLocalizedFailureReason=Mismatched bundle IDs.}}}

### Information:
Instagram IPA v350.0.12
iOS 18.
Sideloading on SideStore.

**Comment by SoCuul** [comment]
Please see #98

Also, for future reference this is not a bug with the tweak itself. If you need any help, feel free to ask over in the discussions tab!

**Comment by SoCuul** [comment]
This seems to be something to do with how SideStore sets the app extension bundle ids, which results in the install failing.

You can try installing without app extensions and see if that fixes the problem.

**Comment by Bryan0211** [comment]
I see. Thanks a lot!
