### ISSUE TITLE
feat: Integrate with GitHub Actions

### ISSUE THREAD

**Issue by zeuikli** [SoCuul/SCInsta#26]
I am designing GitHub Actions workflows, but I encountered an issue with your build.sh script.

https://github.com/zeuikli/BHInsta/actions/runs/8725950614/job/23940117981

Could you please review my workflow to identify a solution for the issue of BHInsta.dylib being unable to be injected by Azule?

![CleanShot 2024-04-18 at 01 13 16@2x](https://github.com/SoCuul/BHInsta/assets/7897668/11f32d2e-0c2a-4436-be93-ceb4f2eccd38)

**Comment by SoCuul** [comment]
Currently the `build.sh` script isn't currently building submodules, which are needed to be injected.

#24 fixes this along with changing from Azule -> Pyzule

I'll try to get it merged as soon as possible to hopefully resolve your issues.

**Comment by SoCuul** [comment]
@zeuikli The new commits should have hopefully fixed the issues you were having. Try pulling the new commits to your fork and hopefully the build should complete!

**Comment by SoCuul** [comment]
@zeuikli do you think you can get this working within the next week? I'm looking to potentially launch v0.4 this week if I have enough time to finish the changes.

**Comment by SoCuul** [comment]
@zeuikli Thank you so much for your help with this one!
