### ISSUE TITLE
todo: remove the stupid meta ai garbage

### ISSUE THREAD

**Issue by SoCuul** [SoCuul/SCInsta#29]
![image](https://github.com/SoCuul/BHInsta/assets/63339559/d76dd275-3628-4995-8f08-b80376a7012c)
![image](https://github.com/SoCuul/BHInsta/assets/63339559/8213d1f8-2caf-4e63-8bbc-8433f8a1b979)

**Comment by SoCuul** [comment]
@asdfzxcvbn @vlourme If either of you have any insight into this, I'd be super grateful for any help I could get.

I've been digging around the app for multiple days now and have found a lot, but still not where it decides if it shows you the meta search bar or the normal one (my alt acc shows the old one still).

There's a possibility that it's controlled by the featureset for each account, which is stored as a numerical value and is pretty much impossible to derive information from.

**Comment by vlourme** [comment]
Meta AI hasn't been rolled out in Europe yet, I don't have the feature with the last version, even with a VPN to the USA. Unfortunately, I cannot provide any help at this moment.

**Comment by asdfzxcvbn** [comment]
i'm getting the ai stuff too. you can hook `-[IGDirectRecipientGenAIBotsResult genAIBots]` to return an empty array and that'll get rid of the suggestions in the first screenshot. and maybe we can just manually remove the ai button from the search bar? if this is fine, i'm happy to open a PR

**Comment by SoCuul** [comment]
> i'm getting the ai stuff too. you can hook `-[IGDirectRecipientGenAIBotsResult genAIBots]` to return an empty array and that'll get rid of the suggestions in the first screenshot. and maybe we can just manually remove the ai button from the search bar? if this is fine, i'm happy to open a PR

Right now I have that alongside some stuff to remove the suggestions from the explore page. Thanks for the offer tho!

If you ever find out about how it's checking eligibility for the meta AI, feel free to share :)
