### ISSUE TITLE
feat: include deb builds in GitHub releases

### ISSUE THREAD

**Issue by difaagh** [SoCuul/SCInsta#35]
I hope you also include the .deb file so users can test the tweak without needing to compile it manually.

**Comment by SoCuul** [comment]
Hi! I've been meaning to add deb releases. Unfortunately I don't have any devices I could test them on.

Would you be able to test some for me?

**Comment by difaagh** [comment]
sorry for late reply, yes i would. i'll try to compile it and back to you again

**Comment by difaagh** [comment]
Thank you @SoCuul Sorry for the late reply. Yes, I would. Do I need to compile it or I can get the deb?

**Comment by SoCuul** [comment]
You can compile it to get the deb. Just check out the theos website!

**Comment by SoCuul** [comment]
I'll make this the main issue for Deb releases

**Comment by SoCuul** [comment]
@difaagh @NHTxAnh Good news! I can guarantee that the next release will have debs alongside IPAs! Been working super hard on the next release (insta changes so much every single update, and the meta ai stuff really added a lot).

**Comment by SoCuul** [comment]
@fetchhh following up on your old issue about debs

**Comment by asdfzxcvbn** [comment]
if a feature works sideloaded it should work through the deb. the only suggestion i have is to not include the sideload fix if being built for jb devices, im happy to open a PR for this

**Comment by SoCuul** [comment]
> if a feature works sideloaded it should work through the deb. the only suggestion i have is to not include the sideload fix if being built for jb devices, im happy to open a PR for this

No worries, already have it implemented locally I just need to push the commits haha
