### ISSUE TITLE
IPA file?

### ISSUE THREAD

**Issue by coqee** [SoCuul/SCInsta#36]
Hi, please dont argue if this is a very dumb question, I dont know anything about ios coding and stuff. But cant you upload the ipa file like bhinsta?

btw, ty very much, I dont have xcode and just have altsore and windows machine

**Comment by SoCuul** [comment]
Hey! So there's nothing actually preventing me from uploading the IPA file, but unfortunately large tech companies have started to DMCA strike entire projects over them uploading IPAs.

Without uploading the IPA, I'm not distributing any of their property which makes this project fully legal 😄
