### ISSUE TITLE
feat: story views change locally

### ISSUE THREAD

**Issue by soh20** [SoCuul/SCInsta#40]
Hi is it possible to change the story views numbers locally that would be amazing!

**Comment by SoCuul** [comment]
Hey! I replied on Reddit as well, but what's the point of changing view counts locally?

**Comment by soh20** [comment]
To fool with our friends. Would be nice to have that feature

**Comment by soh20** [comment]
Is it actually possible to change it?

**Comment by soh20** [comment]
> Hey! I replied on Reddit as well, but what's the point of changing view counts locally?

Is it possible to add this feature? That would be amazing. Also appreciate the work and will donate for it :)

**Comment by SoCuul** [comment]
Unfortunately I just don't feel like it'd fit the scope of this tweak, which is meant for more functional things.

**Comment by soh20** [comment]
Gotcha. If still think it’s easy to implement and have time I would appreciate it to have this feature. Also as a standalone tweak I’m happy too

**Comment by SoCuul** [comment]
Will definitely keep in mind! 😁
