### ISSUE TITLE
Can’t Install in Sileo

### ISSUE THREAD

**Issue by Tomithan** [SoCuul/SCInsta#44]
I can’t install in sileo, dopamine 2.1.4, iPhone 12 Pro 16.5.
![IMG_0756](https://github.com/SoCuul/SCInsta/assets/169421416/4e599b19-4bc9-4174-992e-6ea3216c8fbb)

**Comment by Tomithan** [comment]
It work if I remove bhTwitter, I can’t install both.

**Comment by Tomithan** [comment]
Delete just flex Dylib and plist in filza, and repack deb and it work

**Comment by Tomithan** [comment]
> Facing the same issue, iOS 16.5, Dopamine v2.1.4, Rootless.
> ![image](https://private-user-images.githubusercontent.com/48116275/330230669-0cf77549-d03e-419b-9883-89d83a593d5a.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDU1MzIsIm5iZiI6MTcxNTY0NTIzMiwicGF0aCI6Ii80ODExNjI3NS8zMzAyMzA2NjktMGNmNzc1NDktZDAzZS00MTliLTk4ODMtODlkODNhNTkzZDVhLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwMDA3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDQyMjM1NDZlZDQzM2IyMDlhYWMxMzU3Njk1OGE3YjY4NjYyYjFkZjk4YTJlMDY2MzkxZDNkOTc0NGVmZmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jIQPkDqfizY5PbZLbF2FlSJ4fFMGCe5cec6_EgO_xfg)

https://github.com/Tomithan/SCInsta/releases/download/1/com.socuul.scinsta_0.4.0-2+debug_iphoneos-arm64.deb

**Comment by SoCuul** [comment]
Is there no method to resolve conflicts between dependencies? If not, I can rename the flex dylib within the project to fix this.

**Comment by Tomithan** [comment]
> Is there no method to resolve conflicts between dependencies? If not, I can rename the flex dylib within the project to fix this.

I think not, yes you can rename the flex Dylib, it should be work correctly.

**Comment by SoCuul** [comment]
Now that I think about it, I understand why it has the name libbhFlex. lib + bh + flex

It doesn't make sense to keep that as the name anyways, so I'll update it to fix this. Thanks!

**Comment by SoCuul** [comment]
@Tomithan @davidkh88 Should be fixed in the latest version 😁 
https://github.com/SoCuul/SCInsta/releases/tag/v0.4.1

**Comment by Tomithan** [comment]
> @Tomithan @davidkh88 Should be fixed in the latest version 😁
> https://github.com/SoCuul/SCInsta/releases/tag/v0.4.1

I will try now !

**Comment by Tomithan** [comment]
> @Tomithan @davidkh88 Should be fixed in the latest version 😁
> https://github.com/SoCuul/SCInsta/releases/tag/v0.4.1

Work perfectly, thank you 🙏🏼
