### ISSUE TITLE
unable to access settings

### ISSUE THREAD

**Issue by izichi** [SoCuul/SCInsta#49]
Hello, sir, i have installed the last version of SCInsta, the deb arm64  one (rootless)
Can you help me please? I can't access the settings unless i remove and install the tweak again, i already tried to holding down on settings button, but it doesnt open. I already checked all your github issues topic ([bug: holding down on settings button doesnt open BHInsta settings · Issue #41 · SoCuul/SCInsta (github.com)](https://github.com/SoCuul/SCInsta/issues/41), Bring back dropdown on insta settings click, to still show entrypoint for BHInsta settings)
But still can't manage a way to access the settings without reinstalling the tweak. Can you please fix this issue and maybe add one settings button to show the SCInsta settings entry?
Thank you!

**Comment by SoCuul** [comment]
In the newest version the settings menu has been moved to holding down the Instagram logo on the home page

**Comment by izichi** [comment]
it worked! thank you!!

**Comment by SoCuul** [comment]
Glad it's working now!
