### ISSUE TITLE
Build app using github actions. 

### ISSUE THREAD

**Issue by Joshua-18** [SoCuul/SCInsta#52]
Could it be possible to build from github actions? 
[YTLiteplus](https://github.com/YTLitePlus/YTLitePlus/blob/main/.github/workflows/buildapp.yml) already does that, all we would need to do is provide the ipa.

**Comment by SoCuul** [comment]
Definitely. Someone started working on a workflow a little while ago in #26 but there hasn't been much progress since then.

**Comment by SoCuul** [comment]
I'm going to close this issue for now, but it is on the roadmap for a future release :)
