### ISSUE TITLE
Redirect to Instagram does not work

### ISSUE THREAD

**Issue by InvalidPandaa** [SoCuul/SCInsta#53]
Hello, the Safari extension "Redirect to Instagram" does not work for me. When I open an Instagram page on Safari it doesn't ask to open Instagram app.

**Comment by SoCuul** [comment]
Unfortunately, this a limitation imposed by Apple. The only way to fix this is by using TrollStore or a jailbroken iPhone

**Comment by InvalidPandaa** [comment]
> Unfortunately, this a limitation imposed by Apple. The only way to fix this is by using TrollStore or a jailbroken iPhone 

But it works on other Apps like uYou+ and BHTikTok

**Comment by SoCuul** [comment]
Did you make sure to change the bundle id before sideloading?

**Comment by InvalidPandaa** [comment]
> Did you make sure to change the bundle id before sideloading?

I need to change it? I didn't know 😅
