### ISSUE TITLE
[suggestion] Add blocking reels and hiding explore content

### ISSUE THREAD

**Issue by Defflix** [SoCuul/SCInsta#55]
This is the #1 reason why I used zxcvbn's BHInsta fork. I just want the messaging and stories. I can't be the only one who likes to have instagram distraction-free, right?

It should be easy since these features were already implemented in zxcvbn's fork. 
Block reels commit: https://github.com/asdfzxcvbn/BHInstagram/commit/9b16b9c3e46dd71ffd8b2ede076a449f16675f89
Block explore content commit: https://github.com/asdfzxcvbn/BHInstagram/commit/8002d0a478be6f7fa9c7d40189c35d46dc040fa1

**Comment by SoCuul** [comment]
Both of these features have been implemented in this repo for months at this point haha

- Hide explore grid
- Hide suggested reels

**Comment by Defflix** [comment]
I probably didn’t look into it enough, sorry for that. The features I meant were “Remove feed posts” and “Block all reels”. Block all reels completely disables the loading of reels, so you can’t watch them at all. I personally think they ruined instagram and everyone’s attention span, so I disable them.

These features were last present in zxcvbn's InstaMulti 330.0.0u (before they switched to SCInsta). AFAIK, the version 330.0.0u was using this fork of BHInsta: https://github.com/TbhLovers/VLBHInsta which should contain the Focus features. 
![Focus_features](https://github.com/SoCuul/SCInsta/assets/81767863/4efdefb7-4b16-45fb-b10b-849f87affc1a)

If these features are already present in SCInsta, then I’m either using an older version (zxcvbn's InstaMulti 1.5 which is 4 days old so probably not the case) or I’m literally blind. I triple checked before posting this comment.

**Comment by SoCuul** [comment]
Ah ok, misunderstood you about the hide reels. Will be implemented in a future version.

However regarding the hide explore content, what exactly do you mean by that? When you click on the search tab, the explore grid can already be hidden within the tweak. Additionally ai search results can be removed with the remove meta ai setting.

**Comment by Defflix** [comment]
In the first comment, I thought Hide explore content hid all of the posts, videos and reels on the home page. Later I figured out that the feature that does this is Remove feed posts, as seen in the photo I send in my last comment.

Hide explore content hides all content when you click the explore icon, whereas Remove feed posts removes all posts, videos and reels on the home page. It looks something like this: 
![Remove_feed_posts](https://github.com/SoCuul/SCInsta/assets/81767863/9c63e122-8cab-47c9-b306-af83532d888e)

Good additions to the Focus features could also be
1: No reels scrolling - loads only the clicked reel from messages/feed and removes the ability to scroll to the next reel or refreshing the reels feed (useful when you want to watch only a reel you were sent and want to prevent doomscrolling)
2: Remove reels from feed & explore (search icon) - simply removes all reels from the feed/search (useful when you want to see posts from accounts you follow) (after checking this myself, it seems like instagram makes every video posted a “reel”, so this would theoretically remove all videos from the feed. If there was a way to distinguish between videos and filter out reels, that would be perfect)

I don’t know how to use markdown on github, so sorry if its somewhat confusing

**Comment by SoCuul** [comment]
If you could open a new issue for each of the two requested features, that'd make it much easier to organize 😄 

Use this link to create the bug report: https://github.com/SoCuul/SCInsta/issues/new?labels=bug&title=bug:%20replace%20this%20with%20a%20summary%20of%20the%20issue%20you%27re%20experiencing
