### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Zun4m1** [SoCuul/SCInsta#57]
How come BHinsta is a simple ipa sideload but SCinsta is confusing? Is it required to install all those tools just to sideload? Or just get a insta ipa put it into a folder and sideload.

**Comment by SoCuul** [comment]
Basically, what BHInsta is doing is illegal.

Distributing modified versions of apps is against the TOS of the App Store and is the intellectual property of Meta in this case.

If I were to distribute the IPA for SCInsta, Meta could DMCA strike this repository as it hosted their intellectual property (which they completely have the right to).

Therefore, to make sure nothing like that happens, each person has to build it themselves so no IPA is ever distributed by myself.
