### ISSUE TITLE
Conflict tweaks 

### ISSUE THREAD

**Issue by Tomithan** [SoCuul/SCInsta#64]
Sc insta broke download story post, when it’s enable with nyx on ipa.

https://github.com/SoCuul/SCInsta/assets/169421416/fea52a3b-d680-4316-b2a3-b25206f94c8a

**Comment by SoCuul** [comment]
I see you're using a fork of SCInsta. Please report the bug to them, as configurations with other tweaks are not supported officially by this repo.

**Comment by Tomithan** [comment]
> I see you're using a fork of SCInsta. Please report the bug to them, as configurations with other tweaks are not supported officially by this repo.

Same issue. 

https://github.com/SoCuul/SCInsta/assets/169421416/4c157ec0-5e4a-4e9a-8ae1-8efe2bf83171
