### ISSUE TITLE
Conflict tweaks sc insta from this officially repo

### ISSUE THREAD

**Issue by Tomithan** [SoCuul/SCInsta#67]
Sc insta broke download story post, when it’s enable with nyx on ipa.

https://github.com/SoCuul/SCInsta/assets/169421416/3f2adc4d-3d61-4516-823f-cbbd35664652

**Comment by SoCuul** [comment]
I can not provide support if you are using additional Instagram modifications, as using multiple tweaks can interfere with each other.
