### ISSUE TITLE
Add safari/chrome extension

### ISSUE THREAD

**Issue by RishiSuthar** [SoCuul/SCInsta#68]
(first of all i know you are graduating, congratulations in advance and keep pushing, youre almost at the end! ) 
I owe you a tims for creating this amazing tweak + graduating this year lol 

When you open an instagram link from safari or chrome, if you have the original insta it would direct to this. If you dont have the original insta and only the tweak, the page opens in the browser. It would be cool if it opens in the tweaked app.

**Comment by SoCuul** [comment]
Thank you so much for the kind words!

Unfortunately though, the limitation of not opening Instagram links in the tweaked app is put in place by Apple. There is no way to enable it (without jailbreaking), as it requires permissions only granted by publishing through the App Store.
