### ISSUE TITLE
bug: Media Downloading error 

### ISSUE THREAD

**Issue by Diliphengre** [SoCuul/SCInsta#73]
getting error in reels download.

**Comment by SoCuul** [comment]
TL;DR, those features are not being developed at the moment and are in various levels of working.

**Comment by Diliphengre** [comment]
NEW VERSION WILL COME OR NOT?

**Comment by SoCuul** [comment]
A new version will be released in the next few days which will add support for the latest Instagram version along with some other features/fixes.

Unfortunately, media downloading is still not being worked on at the moment as it is extremely time consuming to fix, considering it needs essentially an entire rewrite.
