### ISSUE TITLE
Reels downloading no longer functions after app restart.

### ISSUE THREAD

**Issue by nanospearing** [SoCuul/SCInsta#78]
After closing and reopening the app it will no longer allow the download function to work. I will allow the selection of the quality, then show a square that says downloading which will disappear shortly. I am on the latest instagram version and the latest tweak built for side loading. If you have any tips or need any more info feel free to reach out!

**Comment by SoCuul** [comment]
https://github.com/SoCuul/SCInsta?tab=readme-ov-file#save-media-partially-broken
Already known to be broken, and already working on a fix!

**Comment by nanospearing** [comment]
> https://github.com/SoCuul/SCInsta?tab=readme-ov-file#save-media-partially-broken Already known to be broken, and already working on a fix!

Ok sweet! Thank you so much for the quick reply, and I wish you the best of luck.
