### ISSUE TITLE
Making our lives easier with Github Actions instead of building it manually with prerequisites needed

### ISSUE THREAD

**Issue by IamNickerson** [SoCuul/SCInsta#79]
Hey Socuul,

I was wondering if using Github Actions to build the SCInsta IPA may be helpful and easier to people who don't know how to build manually or don't want to build by themselves

**Comment by SoCuul** [comment]
Hey! We're actually working on that currently over at #28 but it's been postponed for now as I work on the functionality of the tweak. Plus, it will probably be faster to make a new github action that takes an ipa and just injects it with the latest deb from releases, to prevent the entire build process from being needed.

**Comment by SoCuul** [comment]
Hey! We're actually working on that currently over at #28 but it's been postponed for now as I work on the functionality of the tweak. Plus, it will probably be faster to make a new github action that takes an ipa and just injects it with the latest deb from releases, to prevent the entire build process from being needed.

**Comment by IamNickerson** [comment]
> Hey! We're actually working on that currently over at #28 but it's been postponed for now as I work on the functionality of the tweak. Plus, it will probably be faster to make a new github action that takes an ipa and just injects it with the latest deb from releases, to prevent the entire build process from being needed.

How can i do that?

**Comment by IamNickerson** [comment]
What about Altstore?

**Comment by SoCuul** [comment]
> What about Altstore?

You could use the export ipa option in sideloadly, and then sideload the ipa onto your phone

**Comment by IamNickerson** [comment]
> > > Hey! We're actually working on that currently over at #28 but it's been postponed for now as I work on the functionality of the tweak. Plus, it will probably be faster to make a new github action that takes an ipa and just injects it with the latest deb from releases, to prevent the entire build process from being needed.
> > 
> > 
> > How can i do that?
> 
> You should be able to inject the arm64 deb into the decrypted instagram ipa using something like sideloadly. You also need to add the required "frameworks" with the button inside sideloadly. The framework files can be downloaded from here: https://f005.backblazeb2.com/file/sc-public-files/packages/ios-frameworks/Cephei.zip

I need also to change the app id within sideloadly when injecting the framework inside the decrypted instagram ipa?

**Comment by IamNickerson** [comment]
What file do i need to add as the framework in sideloadly

**Comment by SoCuul** [comment]
Unzip the "Cephei.zip" and add all the folders inside as frameworks

**Comment by IamNickerson** [comment]
I sorted it out by using Zeuikil fork of SCinsta which included the Sideloaded IPA
