### ISSUE TITLE
The tweak does not work on iOS 14

### ISSUE THREAD

**Issue by JohnnyPh** [SoCuul/SCInsta#81]
I have a family member using iOS 14 with instagram version 313.0.2 (Cannot update higher)
The tweak is causing crashing. Could you take a look? I will provide informations you need. Thank you.

**Comment by SoCuul** [comment]
Hi! Which version of iOS 14? As Instagram targets 14.5 if I'm not wrong

**Comment by JohnnyPh** [comment]
> Hi! Which version of iOS 14? As Instagram targets 14.5 if I'm not wrong

It is iPhone 8 Plus on iOS 14.5.1

**Comment by SoCuul** [comment]
Also, I unfortunately am unable to support that version anymore.

Instagram is a very difficult app to develop for as they release new versions frequently and push code changes that don't actually require an app update.

Currently I try my best to support the latest app version on the dev branch, but it's not really possible to support previous versions as there are too many variables to test for.

**Comment by JohnnyPh** [comment]
Okay thank you. I will try to find if there is any alternative

**Comment by SoCuul** [comment]
> Okay thank you. I will try to find if there is any alternative

My best suggestion is to try version 0.3.0 of SCInsta. It definitely doesn't have all of the features that the newest release brings, but it's the closest version I would expect to work with your Instagram app!

https://github.com/SoCuul/SCInsta/releases/tag/v0.3.0

**Comment by JohnnyPh** [comment]
> > Okay thank you. I will try to find if there is any alternative
> 
> My best suggestion is to try version 0.3.0 of SCInsta. It definitely doesn't have all of the features that the newest release brings, but it's the closest version I would expect to work with your Instagram app!
> 
> https://github.com/SoCuul/SCInsta/releases/tag/v0.3.0
okay but I don't have a macbook to build the deb myself. could you help me?

**Comment by JohnnyPh** [comment]
> > Okay thank you. I will try to find if there is any alternative
> 
> My best suggestion is to try version 0.3.0 of SCInsta. It definitely doesn't have all of the features that the newest release brings, but it's the closest version I would expect to work with your Instagram app!
> 
> https://github.com/SoCuul/SCInsta/releases/tag/v0.3.0

okay but I don't have a macbook to build the deb myself. could you help me?

**Comment by SoCuul** [comment]
> > > Okay thank you. I will try to find if there is any alternative
> > 
> > 
> > My best suggestion is to try version 0.3.0 of SCInsta. It definitely doesn't have all of the features that the newest release brings, but it's the closest version I would expect to work with your Instagram app!
> > https://github.com/SoCuul/SCInsta/releases/tag/v0.3.0
> 
> okay but I don't have a macbook to build the deb myself. could you help me?

I just tried to build this version but unfortunately I would have to make a few changes to get it to build. I'm going to be away from my computer for the next few weeks but I'll try to do it when I get back :)

**Comment by SoCuul** [comment]
Unfortunately I have been unable to get a version to work as Instagram now requires ios 15.1 as a minimum to run the app. Sorry about that :/

**Comment by vincent0408** [comment]
Came across this issue just wanted to add it definitely works on iOS 14, at least with 0.6.0
