### ISSUE TITLE
When tap and hold on instagram button to enable the tweak, the app crashes, started occuring on v341.x.x

### ISSUE THREAD

**Issue by Cody47** [SoCuul/SCInsta#82]

**Comment by SoCuul** [comment]
I'm going to be away the next two weeks so I will be unable to fix this soon, but I'll try my best as soon as I get back to my computer.

**Comment by SoCuul** [comment]
Could you possibly provide a crash log?

You can find it in the Settings app under:
- Privacy & Security
  - Analytics & Improvements
    - Analytics Data
      - Instagram-date-othernumbers.ips

Get the app to crash, then find the Instagram log as far down as possible (it should have Instagram.diskwrites or InstagramNotificationExtension under it)

**Comment by SoCuul** [comment]
I've tested the tweak on Instagram v344.0.9 and I haven't experienced any crashes whatsoever. Hopefully your problems should be resolved in the newest Instagram app release.
