### ISSUE TITLE
Doom-Scroll-Free Instagram: Minimal Mode

### ISSUE THREAD

**Issue by labib2002** [SoCuul/SCInsta#92]
I’d love an option that turns Instagram into a distraction-free app focused on chats & stories, similar to "Unhook" extension for YouTube.

Features:
Stories from Followed Accounts Only: Show only stories from followed users. Hide the main feed, explore page, and suggestions.

Direct Messages (Chats): Keep full access to direct messages and group chats.

Reels Only in Chat: Allow reels to be only through links/shares in chats. Disable Reels tab & scrolling, with option to disable comments.

Disable Reels Feed & Explore Page: Completely hide the Reels feed and Explore tab to prevent endless scrolling.

**Comment by SoCuul** [comment]
Right now, you can already disable the reels tab and the explore feed, along with only showing posts that are from users you are following.

I'd be interested in adding a setting to prevent scrolling when viewing a reel from direct messages

**Comment by labib2002** [comment]
Fantastic to hear you're interested! I took a look at several other projects, they could allow you to hide some pages but aren't feature complete and usually crash. I looked into the features you mentioned and used them to great effect so far, the hide reels and explore tabs(a great feature by another tweak is hide the explore but keep the search part of it) 

the only 2 remaining features for that are: 

- hiding the posts in the main page, keeping it only for stories or laying the stories in a post-like fashion making the page less empty.
- and disabling the scroll.

**Comment by SoCuul** [comment]
If you enable "Hide explore posts grid" and "Hide trending searches" you should be left with just the search bar on the explore page

**Comment by SoCuul** [comment]
I'd encourage taking a look at [v0.6.0](https://github.com/SoCuul/SCInsta/releases/tag/v0.6.0)
Might include some stuff you're interested in 👀

**Comment by veerravuri** [comment]
+1 I am very interesting in this release. I will literally pay u to maintain this version :)

**Comment by labib2002** [comment]
> +1 I am very interesting in this release. I will literally pay u to maintain this version :)
> 
> I am jailed unfortunately so the deb files don't work with design. awaiting this release.

Nice! i'm very pleased to know someone else's interested. take a look at the building scinsta page in the wiki. i'm seeing if i can get the ipa myself

**Comment by labib2002** [comment]
> +1 I am very interesting in this release. I will literally pay u to maintain this version :)
> 
> I am jailed unfortunately so the deb files don't work with design. awaiting this release.

yup just got the ipa, try it out

**Comment by SoCuul** [comment]
> +1 I am very interesting in this release. I will literally pay u to maintain this version :)
>
> I am jailed unfortunately so the deb files don't work with design. awaiting this release.

@veerravuri Unfortunately I don't have any jailbroken device to test this tweak on :(

**Comment by veerravuri** [comment]
> > +1 I am very interesting in this release. I will literally pay u to maintain this version :)
> > I am jailed unfortunately so the deb files don't work with design. awaiting this release.
> 
> Nice! i'm very pleased to know someone else's interested. take a look at the building scinsta page in the wiki. i'm seeing if i can get the ipa myself

Did it work? Will this tweak work on jailed devices? Its a simple tweak so I’d think so
