### ISSUE TITLE
error message box pop up while using sideloadly

### ISSUE THREAD

**Issue by goffena** [SoCuul/SCInsta#99]
![螢幕擷取畫面 2024-10-04 174248](https://github.com/user-attachments/assets/d776a3df-f751-4a28-9bd1-699efdedb988)

sorry i'm a noob for this, i follow the steps in your repository, and successfully download the ipa from workflow
but when i try to sideload it, this message pop up, and tbh i can't understand what's going on
would you please take a look and share some advice?

really appreciate it

**Comment by ic3dlem0n** [comment]
are u on ios 18

**Comment by ic3dlem0n** [comment]
the fix is to use a older instagram ipa it worked for me if u want download from my latest workflow

**Comment by goffena** [comment]
I’m on iOS 17.7 
I use v350.0.0 downloaded from some decrypt site

**Comment by goffena** [comment]
So which version of instagram that you use

**Comment by SoCuul** [comment]
v350.0.12 as stated in the readme and the release page

**Comment by goffena** [comment]
can't find this version sorry

**Comment by ic3dlem0n** [comment]
yea i couldnt find that version either but download the ipa from my workflow its not the latest version but it has all the latest insta features

**Comment by goffena** [comment]
do you mind to share that workflow?

**Comment by ic3dlem0n** [comment]
https://github.com/ic3dlem0n/SCInstaforkleeel/actions/runs/11205355838

**Comment by goffena** [comment]
Success
Thanks a lot
